spring.application.name=taxis

# Server
server.port=8081

# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/taxis_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# Docker Compose
spring.docker.compose.enabled=true
